language: node_js
node_js:
  - "10"
install:
  - npm install
script:
  - npm test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_5c9a41d00b85_key -iv $encrypted_5c9a41d00b85_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public $user@$ip:/root/code/test
  on:
    branch: master
addons:
  ssh_known_hosts: $ip
cache:
  directories:
    - "node_modules"

